[package]
name = "rtweekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
image = "0.24.3"
threadpool = "1.8.1"
num_cpus = "1.13.1"